plugins:
  - name: orthanc-dicomweb
    version: 1.17
    filename: libOrthancDicomWeb.so

  - name: orthanc-neuro
    version: 1.1

  - name: orthanc-python/debian-bullseye-python-3.9
    version: 4.2
    filename: libOrthancPython.so

  - name: orthanc-explorer-2
    version: 1.4.1
