services:
  mongodb:
    image: mongo:latest
    ports:
      - 27027:27017
    volumes:
      - mongodb_volume:/data/db
    networks:
      - girder_orthanc_network

  girder:
    image: girder/girder:latest
    depends_on:
      - mongodb
    ports:
      - 8084:8080
    command: --host 0.0.0.0 --database mongodb://mongodb:27017/girder
    networks:
      - girder_orthanc_network

  orthanc:
    image: jodogne/orthanc-plugins:latest
    ports:
      - 8043:8042
    volumes:
      - orthanc_volume:/var/lib/orthanc/db
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - girder_orthanc_network

  apache:
    image: httpd:latest
    ports:
      - 81:80
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - girder
      - orthanc
    networks:
      - girder_orthanc_network

networks:
  girder_orthanc_network:

volumes:
  mongodb_volume:
  orthanc_volume:
